#
# Packages external to NOvA. Order matters: keep SoftRelTools first.
#
SoftRelTools : HEAD
#
# NOvA Offline packages go here
#
AirShower           : art2root6-integration-trunk.b
Alignment           : art2root6-integration-trunk.b
AnalysisSkimmer     : art2root6-integration-trunk.b
BreakPointFitter    : art2root6-integration-trunk.b
BremShowerFilter    : art2root6-integration-trunk.b
CAFAna              : art2root6-integration-trunk.b
CAFMaker            : art2root6-integration-trunk.b
CAFReweight         : art2root6-integration-trunk.b
CalHit              : art2root6-integration-trunk.b
Calibration         : art2root6-integration-trunk.b
CalibrationUtils    : art2root6-integration-trunk.b
CalibrationDataProducts : art2root6-integration-trunk.b
Calibrator          : art2root6-integration-trunk.b
CelestialLocator    : art2root6-integration-trunk.b
ChannelInfo         : art2root6-integration-trunk.b
CMap                : art2root6-integration-trunk.b
Commissioning       : art2root6-integration-trunk.b
CosmicExposureInfo  : art2root6-integration-trunk.b
CosRej              : art2root6-integration-trunk.b
CVN                 : art2root6-integration-trunk.b
DAQ2RawDigit        : art2root6-integration-trunk.b
Database	    : art2root6-integration-trunk.b
DataQuality         : art2root6-integration-trunk.b
DDTAnalysis         : art2root6-integration-trunk.b
DDTConverters       : art2root6-integration-trunk.b
DDTEventDisplay     : art2root6-integration-trunk.b
DDTMonopole         : art2root6-integration-trunk.b
DDTTools            : art2root6-integration-trunk.b
Demo		    : art2root6-integration-trunk.b
DetectorPerformance : art2root6-integration-trunk.b
DiscreteTracker     : art2root6-integration-trunk.b
DiskUsage           : art2root6-integration-trunk.b
DQSpillFlags        : art2root6-integration-trunk.b
DSOResultPlotter    : art2root6-integration-trunk.b
ElasticArms         : art2root6-integration-trunk.b
Eval	            : art2root6-integration-trunk.b
EventDisplay        : art2root6-integration-trunk.b
EventDisplayServices : art2root6-integration-trunk.b
EventGenerator      : art2root6-integration-trunk.b
EventSummary        : art2root6-integration-trunk.b
EWCosmicAnalyzer    : art2root6-integration-trunk.b
Filter              : art2root6-integration-trunk.b
FNEX                : art2root6-integration-trunk.b
FuzzyKVertex        : art2root6-integration-trunk.b
g4nova              : art2root6-integration-trunk.b
GenieSNova          : art2root6-integration-trunk.b
Geometry            : art2root6-integration-trunk.b
GeometryObjects     : art2root6-integration-trunk.b
HoughTrack          : art2root6-integration-trunk.b
HoughTransform      : art2root6-integration-trunk.b
HoughVertex         : art2root6-integration-trunk.b
IFDBSpillInfo       : art2root6-integration-trunk.b
LEM                 : art2root6-integration-trunk.b
MCCheater           : art2root6-integration-trunk.b
MCCheckOut          : art2root6-integration-trunk.b
MCReweight          : art2root6-integration-trunk.b
Metadata            : art2root6-integration-trunk.b
MEFinder            : art2root6-integration-trunk.b
MockDataDAQ         : art2root6-integration-trunk.b
Monopole            : art2root6-integration-trunk.b
MonopoleMC          : art2root6-integration-trunk.b
MuonRemove	    : art2root6-integration-trunk.b
NCID                : art2root6-integration-trunk.b
NDAna               : art2root6-integration-trunk.b
NDRockMuon          : art2root6-integration-trunk.b
NewEventDisplay     : art2root6-integration-trunk.b
NovaFTS             : art2root6-integration-trunk.b
NovaSimMixer        : art2root6-integration-trunk.b
NueSandbox          : art2root6-integration-trunk.b
NumuEnergy          : art2root6-integration-trunk.b
NumuSandbox         : art2root6-integration-trunk.b
NusSandbox          : art2root6-integration-trunk.b
OnlineMonitoring    : art2root6-integration-trunk.b
OscLib              : art2root6-integration-trunk.b
PhotonTransport     : art2root6-integration-trunk.b
Preselection        : art2root6-integration-trunk.b
ProductMorgue       : art2root6-integration-trunk.b
QEEventFinder       : art2root6-integration-trunk.b
RawData             : art2root6-integration-trunk.b
ReadoutSim          : art2root6-integration-trunk.b
RecoBase            : art2root6-integration-trunk.b
RecoBaseHit         : art2root6-integration-trunk.b
RecoJMShower        : art2root6-integration-trunk.b
RecoValidation      : art2root6-integration-trunk.b
RecVarPID           : art2root6-integration-trunk.b
ReMId               : art2root6-integration-trunk.b
RunHistory	    : art2root6-integration-trunk.b
ShowerE             : art2root6-integration-trunk.b
ShowerLID           : art2root6-integration-trunk.b
Simulation          : art2root6-integration-trunk.b
Slicer              : art2root6-integration-trunk.b
SRT_NOVA            : art2root6-integration-trunk.b
StandardRecord      : art2root6-integration-trunk.b
SummaryData         : art2root6-integration-trunk.b
Supernova           : art2root6-integration-trunk.b
SupernovaUtilities  : art2root6-integration-trunk.b
TDSlicer            : art2root6-integration-trunk.b
TimingFit           : art2root6-integration-trunk.b
TrackFit            : art2root6-integration-trunk.b
TriggerMonitoring   : art2root6-integration-trunk.b
Utilities           : art2root6-integration-trunk.b
Validation          : art2root6-integration-trunk.b
VertexDT            : art2root6-integration-trunk.b
VertexFinder        : art2root6-integration-trunk.b
XnuePID             : art2root6-integration-trunk.b
XSecReco            : art2root6-integration-trunk.b
ZukCluster          : art2root6-integration-trunk.b
#
# NOvADDT packages go here
#
CalibrationTriggers     : v11_00_04-br
DAQStatusTriggers       : v11_00_04-br
DAQUnpackUtils          : v11_00_04-br
DDTBaseDataProducts     : v11_00_04-br
DDTCore                 : v11_00_04-br
DDTDemo                 : v11_00_04-br
DDTGlobalConfigurations : v11_00_04-br
DDTMessageSender        : v11_00_04-br
DDTPrescale             : v11_00_04-br
DDTUtilities	        : v11_00_04-br
ExoticsTriggers         : v11_00_04-br
HitSlicers              : v11_00_04-br
HitSorters              : v11_00_04-br
MoonShadowTrigger       : v11_00_04-br
NuETriggers             : v11_00_04-br
NuMuTriggers            : v11_00_04-br
OnlineCalibration       : v11_00_04-br
PatRec		        : v11_00_04-br
SlowMonopoleTrigger     : v11_00_04-br
Statistics              : v11_00_04-br
SuperNovaDDT            : v11_00_04-br
Tracking                : v11_00_04-br
#
# NOvA Online packages go here
#
DAQChannelMap           : R11_Branch
DAQDataFormats          : R11_Branch
DAQMessages             : R11_Branch
DAQQualityCheck         : R11_Branch
DatabaseUtils           : R11_Branch
EventDispatcher_CommandSet : R11_Branch
NovaDAQConventions      : R11_Branch
NovaDAQMonitorClient    : R11_Branch
NovaDAQUtilities        : R11_Branch
NovaDatabase            : R11_Branch
NovaTimingUtilities     : R11_Branch
PackageVersion          : R11_Branch
RawFileParser           : R11_Branch
rms                     : R11_Branch
ShmMilliBlock           : R11_Branch
ShmRdWr                 : R11_Branch
#
# setup package
#
setup               : art2root6-integration-trunk.b
