#!/bin/bash
#
# Alex Himmel ahimmel@fnal.gov
#

if echo $@ | grep "\-h" >> /dev/null; then
    echo "merge_from_trunk <rev>"
    echo "This script merges a series of specific commits from the trunk into this branch and commits it, copying the original commit message."
    exit 0
fi


for rev in $@; do
    echo "Processing revision $rev"

    # Find the full url of our current location on the branch
    branchurl=`svn info | grep 'URL' | awk '{print $NF}'`

    # Find the name of the branch
    branchname=`echo $branchurl | egrep -o '(branches)/[^/]+|trunk' | egrep -o '[^/]+$'`

    # Create the url for this location on the trunk
    trunkurl=`echo $branchurl | sed -e "s|branches/$branchname|trunk|"`

    if [[ $branchname == "trunk" ]]; then
        echo "Already on the trunk, nothing to do."
        exit 0
    fi

    # Store the commit message to put into the later merge commit
    tmp_message_file=`mktemp -t $USER.merge_from_trunk.XXXXXXXXXX` || exit 1
    echo "Merging revision $rev from trunk to $branchname." > $tmp_message_file
    svn log $trunkurl -r $rev | tail -n +4 | head -n -1 >> $tmp_message_file

    echo "svn merge -c $rev $trunkurl"
    svn merge -c $rev $trunkurl 
    retval=$?

    if [[ $retval != 0 ]]; then
        echo "Merge failed, probably due to a conflict, stopping here. You probably missed a previous commit. Start over with:"
        echo "svn revert --recursive . "
        exit $retval
    fi

    cat $tmp_message_file

    echo "svn commit -F $tmp_message_file"
    svn commit -F $tmp_message_file
    retval=$?

    if [[ $retval != 0 ]]; then
        echo "Commit failed."
        exit $retval
    fi

    rm $tmp_message_file
    echo
done

#
# All steps successfully complete, clean up
#
echo "Success!"

