BINS := update-release \
	nova_srt_bootstrap \
	srt_environment_nova \
	novasoft_build \
        ack \
	addpkg_svn \
        svn_branch_commit \
	merge_from_trunk \
	merge_from_anywhere \
  srt_parallel

SCRIPTS := $(BINS)

########################################################################
include SoftRelTools/standard.mk
