#!/bin/bash

if [ -z "$EXTERNALS" ]; then
    echo "Must source nova setup before executing the script."
    echo 'Actually just need to know about $EXTERNALS environmental variable.'
    echo 'If you are using this script as a first time import of externals make youreself a directory and set the $EXTERNALS variable.'
    exit 1
fi

# An offsite maintainer might have a different local username than the FNAL kerberos principal
# Can change this variable to allow kerberized scp
script_user=`whoami`
novavmhost='novagpvm04.fnal.gov'
fnalvm="$script_user@$novavmhost"

cd ${EXTERNALS}
mkdir tars
cd tars

# get the pull script
wget http://scisoft.fnal.gov/scisoft/projects/art/v1_12_01/pullProducts-v1_12_01
chmod +x pullProducts-v1_12_01
./pullProducts-v1_12_01 ${EXTERNALS} slf6 nu s5-e6 debug
./pullProducts-v1_12_01 ${EXTERNALS} slf6 nu s5-e6 prof
./pullProducts-v1_12_01 ${EXTERNALS} slf5 nu s5-e6 debug
./pullProducts-v1_12_01 ${EXTERNALS} slf5 nu s5-e6 prof

# pull novadaq tars
wget http://scisoft.fnal.gov/scisoft/packages/novadaq/v03_00_02/novadaq-03.00.02-slf5-x86_64-e6-debug.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/novadaq/v03_00_02/novadaq-03.00.02-slf5-x86_64-e6-prof.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/novadaq/v03_00_02/novadaq-03.00.02-slf6-x86_64-e6-debug.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/novadaq/v03_00_02/novadaq-03.00.02-slf6-x86_64-e6-prof.tar.bz2


# pull novaddt tars 
wget http://scisoft.fnal.gov/scisoft/packages/novaddt/v02_02_01/novaddt-02.02.01-slf5-x86_64-e6-debug.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/novaddt/v02_02_01/novaddt-02.02.01-slf5-x86_64-e6-prof.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/novaddt/v02_02_01/novaddt-02.02.01-slf6-x86_64-e6-debug.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/novaddt/v02_02_01/novaddt-02.02.01-slf6-x86_64-e6-prof.tar.bz2

# pull cstxsd v4.0.0a                                                                                                                          
wget http://scisoft.fnal.gov/scisoft/packages/cstxsd/v4_0_0a/cstxsd-4.0.0a-source.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/cstxsd/v4_0_0a/cstxsd-4.0.0a-slf6-x86_64-e6.tar.bz2

wget http://scisoft.fnal.gov/scisoft/packages/cstxsd/v4_0_0a/cstxsd-4.0.0a-slf5-x86_64-e6.tar.bz2

# pull the artdaq_core tar
scp ${fnalvm}:/grid/fermiapp/products/nova/externals/artdaq_core/artdaq_core_v1_03_05.tar ./

# pull NumiBeamDB
scp ${fnalvm}:/nusoft/app/externals/NumiBeamDB/v2_1_2-2014-09-03.tar.gz ./

# pull Valgrind
scp ${fnalvm}:/nusoft/app/externals/valgrind/valgrind_v3_6_1.tar.bz2 ./


cd $EXTERNALS
tar xf tars/novadaq-03.00.02-slf5-x86_64-e6-debug.tar.bz2
tar xf tars/novadaq-03.00.02-slf5-x86_64-e6-prof.tar.bz2
tar xf tars/novadaq-03.00.02-slf6-x86_64-e6-debug.tar.bz2
tar xf tars/novadaq-03.00.02-slf6-x86_64-e6-prof.tar.bz2


tar xf tars/novaddt-02.02.01-slf5-x86_64-e6-debug.tar.bz2
tar xf tars/novaddt-02.02.01-slf5-x86_64-e6-prof.tar.bz2
tar xf tars/novaddt-02.02.01-slf6-x86_64-e6-debug.tar.bz2
tar xf tars/novaddt-02.02.01-slf6-x86_64-e6-prof.tar.bz2


tar xf tars/cstxsd-4.0.0a-source.tar.bz2
tar xf tars/cstxsd-4.0.0a-slf6-x86_64-e6.tar.bz2
tar xf tars/cstxsd-4.0.0a-slf5-x86_64-e6.tar.bz2

tar xf tars/artdaq_core_v1_03_05.tar 

tar xf tars/valgrind_v3_6_1.tar.bz2

# If this is a first time install, the NumiBeamDB directory won't exist yet.
# Is this still necessary in the IFDB era?
if [ ! -d "NumiBeamDB" ]; then
  mkdir NumiBeamDB
fi

cd NumiBeamDB
tar xf $EXTERNALS/tars/v2_1_2-2014-09-03.tar.gz

cd $EXTERNALS

# First time install should first download upd product
# Used to be part of the ups install, probably an oversight in the newest version.
if [ ! -d "upd" ]; then
  cd tars

  wget http://scisoft.fnal.gov/scisoft/packages/upd/v5_0_1/upd-5.0.1-noarch.tar.bz2
  wget http://scisoft.fnal.gov/scisoft/packages/upd/v5_0_1/upd-5.0.1-source.tar.bz2

  cd $EXTERNALS
  tar xf tars/upd-5.0.1-noarch.tar.bz2
  tar xf tars/upd-5.0.1-source.tar.bz2
fi

source $EXTERNALS/setup
setup upd

upd install lid			v01.00
upd install eid			v01.00
upd install hmatrix		v01.00
upd install lemlittle		v01.02
upd install qepid		v01.00
upd install remid		v01.00
upd install ucana		v01.02
upd install rvp                 v01.00
upd install calibcsvs           v01.00
upd install sam_web_client	v1_8
upd install jobsub_tools	v1_3_1_1_2
upd install condb               v2_0b
